apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: {{ .Release.Name }}
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            endpoint: 0.0.0.0:3030
    exporters:
      debug:
      loki:
        endpoint: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
      prometheus:
        endpoint: 0.0.0.0:8889
    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [loki]
        traces:
          receivers: [otlp]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          exporters: [debug, prometheus]