---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoring-source
  namespace: monitoring
spec:
  interval: 1m0s
  ref:
    branch: otel
  url: https://github.com/bicyclecat/kbot