---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  chart:
    spec:
      chart: ./otel/fluent-bit
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: monitoring-source
  interval: 2m0s