# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Dummy comment added

replicaCount: 1
image:
  registry: "docker.io"
  repository: "bicyclecat"
  tag: "v1.0.7-3aa8c83"
  os: linux
  arch: amd64
#podAnnotations:
#  sidecar.opentelemetry.io/inject: "true"
secret:
  env: "TELE_TOKEN"
  name: "kbot"
  key: "token"
securityContext:
  privileged: true
env:
  metricsHost: "otel-collector.monitoring.svc:4317"
