apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kbot-letsencrypt-prod
  namespace: demo
spec:
  acme:
    email: edelweissman@yahoo.com
    privateKeySecretRef:
      name: kbot-letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: contour