apiVersion: v1
kind: Secret
metadata:
    name: kbot
    namespace: kbot-test
type: Opaque
data:
    token: ENC[AES256_GCM,data:fhyqzKtZC437ntLrQBHWNnoyw4+ApPd+74aCnJWOWorNLNpDz85TTnMZP5PUyAobpN01HVyAwN7LDypgEGeQBg==,iv:IXhAnJfubmtqm8chAQS98hUQF/pRRAg3iEfFBvCJf8w=,tag:YzsE+KxtiQMM04SPXW2CoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-21T17:49:00Z"
    mac: ENC[AES256_GCM,data:2ji3smucDwTvSjRDobeVtnEQxVmvi3pWX0wUeeW/KBJO1ixCYkcOI7VvMjpw4HYkTFlomg3NHRE0f6MoIadEqfJYssrDFT/phyPvbZAGuQZ6lCAcBmelR3xoYKRn3+QEMzCKDW30TLGlGYevjCVc45XQc1Xej4+yEoB9wBixvxM=,iv:hRDUzblV5hCt08swEpv2oy2K1vb2IXign1t7qofJ05w=,tag:CQn5/2+r++gKxdSBAo+cqA==,type:str]
    pgp:
        - created_at: "2023-12-21T17:49:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxIitMCJCXCOAQ/8DiAHy6UvyUnMoqkBKDdFm2DylnSuM32Ecf3idg3XJ3pA
            JVVTepsUgVItf/UHkogPRS0A/Nh/w9iF6KIz8smXki1e543/yZTJRuaiqz0U7v6x
            jU+YsLiDDVrM0qTx087Qx113SU+um+scYQRasD+dLclm/bpPzDYa8W6rXeSQkm+D
            EiCOhMMPOv7a8CA39usmsLslrBB4+ZG62rXb5HkloXGoJzsS9LIhNgM22s+2RLGj
            A3XGpBh0XuuapzBSry1QG0EcV6ndAgGfSviz6EqTSpihCANvT6tftHnr3FNSYpeh
            rNuBjOqJNM17cRAbRbO9hI1OA/R89+r6uCSV7ZsbxJWzE/+pbh98Yl/bArU68wVP
            +dpmUFc7AQS00ec/5V4N9KI8tSO1+wQH1FVTsAEineCwwdIFp5EvxCdtXu5RjgQ3
            bJyHwtuTeUo1xrkUX6AIaohVMQ3uZi8Rzr1PuZMqcsBcSbwanxSjepD5wB6UzkIE
            bP7nuGGNLDGw67CwR+7TDNOtQBIPU1T4bXRSeW3fvTaGtpDVzPT/Vp9G4KJ1sC5P
            BtsriiXw4PYeh5S5ZW9AvbXV9HqPEKFetq3Vl6i7seHzo4v3i2s2qZJ7kU7NsOD4
            mEhPY5BAJqIg6CnrKn7Z0tZdtWX22Oc64L8Y6PmE5zirAzHr2c7mZ7vNn0HMbJDS
            UQEId0Pm+RDeWA+kbIyZrhJ2uoyDTVDMd/7BrMSoAaW50lvPWJr1p2DU6kWnZMHM
            3HzYtdSqTso19BLozo9HN6uof0DewCk62ZnbUskLyHYOdA==
            =Yv7z
            -----END PGP MESSAGE-----
          fp: cdff97e6e1fec16d3d56489f2786971af7911490
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
