apiVersion: v1
kind: Secret
metadata:
    name: kbot
    namespace: kbot
type: Opaque
data:
    token: ENC[AES256_GCM,data:2/Vtr+sWtsS8AvbG+PfjOCgTmy7iraEv4Al+HuCTJ/Eez5TOWzl0jjFUytWDX7JYZ0upehfgdfeB1/+ftecjSw==,iv:naLenSQL9SnXglpjwXAtpNa6KOapY7GriOzqx2TMJf4=,tag:aTUq9o7L3JSyWG1vKC1b8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-24T13:49:47Z"
    mac: ENC[AES256_GCM,data:LGbWO3NEA2YyVXIvTSQoyjPMwzUUPbqIpaVTtXK1bYZvLl2sFSZa/wo03vSM4ww9ykr9EoE28eD7kSjG9kGwZ+LQEGx3/hKtW4zio5XOlJ6D1dNjWUR1UJt+2tICFodeCHXviONKR+hpbK6dAH60JNZYgPe0J+sWTRFYI5nFAEU=,iv:Gwnd5TdwVHd25LZBoe8fAq9XWpp0cffHL1zVEzxut3I=,tag:UTsw5w0P+bclXd/+PplCEA==,type:str]
    pgp:
        - created_at: "2023-12-24T13:49:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+nW9T/753wJARAAmd/t52KzGpdqhtATCpjcN3jRVkGzOFww/BUy2cntB9+f
            AwjGOhBdcx9GER+5Sdqvdr2krb8Kkbxl8758qjEID0CO/SGaH8GalcNRFgf10VLF
            kpkHr4JL5zeV2hb+hTW27uwnFQE5tBRQ584d0fV3Ce6keuNS7Ye1tSeRi3qkPA13
            0ZS9i2pAv+dQt3K8tDzbzglh2dQFNZZfNJSWYXid+jAFlbYki+eNfaqcZhnwwdg1
            Kkw/cwrBgMl70bmZ8Lx12DhnnrfgJgOKmTt5sTYvdSzFG6Klom5CxG4SsceiAvMe
            4Y1B1q2fQkKpb39v140G5fOjrE7FA06wfI7r7miDgLQbQRnQtn17nUA/leusCiB+
            tujQLnZX3p9Dxoa0EHWoWYs4DQTdwBRPGGxWHRBok+J0b7fX/L/AtBbeuIIHpv14
            0auJ7lj+Z9WGikolM2Qi6rb2K11PegThxzJw0YYQEpcQ5ixTpH8m+hSQWm1HK9vU
            +pGBRey7oewsgdLM01qc6LZkI2Otx6rtb7ZDCHbLsmvBxiK/jlWzYsQDpC0MZWXv
            Ln+ZK5eqfiak37SD3XbsCnPNI/Xkbsupxl6dp4H0j4ITBFCfWyUje90tfbgcJS7y
            baSI7taeovppWr+TT5eBT1/tuQwvud7XYKiAZNFA4uEO6JT2UjPu24L6h2r2vu3S
            UQGra8Qm+Al2BoI99qKDAAeoHEoZR+r9BdsStxPUXIU6/vDJG9ctmnItEev//Fc7
            sy6snricvctKVHM47QNhLi7+2W2dndmBycQ/4NT+VAmzjQ==
            =CfsT
            -----END PGP MESSAGE-----
          fp: 390c5bf59d13237b46589e5abcec1ec1a9f19ffe
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
