apiVersion: v1
kind: Secret
metadata:
    name: kbot
    namespace: kbot
type: Opaque
data:
    token: ENC[AES256_GCM,data:Y8AqRwh6n2Izs4a/rINkim1BXoEyV250kmOSnlVmxaeH/m44LR32rTHdybh2IxVCw868WIxzGFykSemCJ5pt2Q==,iv:IVbjoBCbHgV+PDccKmUcW0a7ITZh7YtDR4wLpzVz1FI=,tag:T/Lfd3QKdqVYNwFBBNDBlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-22T21:40:03Z"
    mac: ENC[AES256_GCM,data:O6aNq4g1eKSmKTbMWMegHZGr/njVgf95PzeMvQ/+WDbWxWplHpdJhcN8Ouc5JeDkk6KdOM6UOrBc2uF1nj0yhC/m1enO3/mn1V1+RzmhZs0fGNlbyQrarPgOmJDBijplQxfCCI88FZOjQYj401i22bqvjLiB6vZBJ6Ngr0G+LXg=,iv:3l61m2aDRWB198Fxr9qtlLQR/maVfX/g6YBmz+YebOQ=,tag:0o9+eyCQkkTRPLblTpqdVA==,type:str]
    pgp:
        - created_at: "2023-12-22T21:40:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA64se6xBsfaZARAAy4bv39DehOZV/HJ4YdmXbEH3Wyq6rrhWATbu3WvWjhxn
            2kAN9bM2rWTm4FPCFU7U990pgQ8ebHVYxkzLcEYO5f3ZSDSEjrscFLg1fCw1z7r4
            C+Smohvik9cmyIea70igO5IsX5C55jf9rg2/GSgCQPdS7EbC02wLdFWc5Y4I4TDq
            AkGVdO+3Fmi6ZXKzK701kXDGKBYogU3VxccX1oARGV181cmXCZqEgQ7e9sOXDEpj
            hLkQ8xmeqlj6mw7lCfuWUs1L8RCI7DBs26CIARQFk14pwbHnual2jA3IBL+xd2SQ
            NSaMhJzhqUdku4Y/DplWk29qcU0fYa93YaMrbp6yx26XiiGC8Gb9BmuUF7D7kNlA
            qYkAxRuaXyUqNTE/PomxGxUH7wmMJVUSxIQ7QK5YWRQBkhdmIHUYV2KOKs+ht0gv
            qfzqIqGkwoKtsiOTAbm+Q9d1hcLyfersfI9i5qvyEFfKw1rc9sWz0hyire6RWdZK
            oC+ECyylDQrfvpMQUN3bVAtgNskXqh0+QCkfdtES50mlVQXm6hszh0rDOh7IZCvE
            2FfWQtgvL2sKs99HyHqbLGc3uIQuEA80+/Jm25pQyB/yj06KF7gi6hfUIBRev8bk
            MSLSNHYLcNRfKDRIP5EZw0aUtZj8E7RhidJbgfPiE+WtybvcjBXSzopm7MvG6pjS
            UQERTpOZNzz4Wg71o3gTuPBPBXKp12F7L+b12xZOdqFmLiplPYZR3dH7FAkZaD0P
            sYPoSBr/gi+CJ7dstfq+SpjX3dUezjSJfsCkz1E1mmrcpA==
            =an4X
            -----END PGP MESSAGE-----
          fp: c0f77b0cee713738a90494ffb40c49b2e1ad1e1b
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
